add -r option

diff --git a/system/xbin/systemize b/system/xbin/systemize
--- a/system/xbin/systemize
+++ b/system/xbin/systemize
@@ -8,12 +8,19 @@ ID="terminal_systemizer"
 
 # Detect root
 _name=$(basename $0)
-ls /data >/dev/null 2>&1 || { echo "$ID needs to run as root!"; echo "type 'su' then '$_name'"; exit 1; }
+ls /data >/dev/null 2>&1 || {
+  echo "$ID needs to run as root!"
+  echo "type 'su' then '$_name'"
+  exit 1
+}
 
 # Magisk Mod Directory
 MOUNTPATH="/data/adb/modules"
 MODDIR="$MOUNTPATH/$ID"
-[ ! -d $MODDIR ] && { echo "Module not detected!"; exit 1; }
+[ ! -d $MODDIR ] && {
+  echo "Module not detected!"
+  exit 1
+}
 
 # Load mod-util.sh
 . $MODDIR/mod-util.sh || exit $?
@@ -29,7 +36,8 @@ VERLOG=/data/local/tmp/$ID-verbose.log
 oldVERLOG=/data/local/tmp/$ID-verbose-old.log
 
 # Start Logging verbosely
-mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null
+mv -f $VERLOG $oldVERLOG 2>/dev/null
+mv -f $LOG $oldLOG 2>/dev/null
 set -x 2>$VERLOG
 
 # Main
@@ -38,7 +46,7 @@ set -x 2>$VERLOG
 # > Rather than editing the default vars above.
 
 help_me() {
-  cat << EOF
+  cat <<EOF
 $MODTITLE $VER($REL)
 by $AUTHOR
 
@@ -50,11 +58,12 @@ Options:
     -f                     use 'Set SELinux' in the session for faster app listing
     -a [package name]      systemizes the package name(s) provided
     -p [package name]      systemizes the package name(s) provided to priv-app only
+    -r [package name]      revert the package name(s) provided to normal app
     -d [apk dir]           systemizes the apk(s) provided
     -l                     list all systemized apps
     -h                     show this message
 EOF
-exit
+  exit
 }
 
 use_aapt=false
@@ -116,20 +125,26 @@ list_installed_apps() {
         se_set=false
       fi
     fi
-    rm $LISTFILE 2>>$LOG; app=(); app1=(); app2=();
+    rm $LISTFILE 2>>$LOG
+    app=()
+    app1=()
+    app2=()
     for i in $($method | sed 's/.*://'); do
-      h=$(((h+1)%4))
+      h=$(((h + 1) % 4))
       Spinner "Loading Apps"
-      if ! dumpsys package $i | grep -qEm1 -e "($detect)" - ; then
+      if ! dumpsys package $i | grep -qEm1 -e "($detect)" -; then
         app=${i##*/}
         package=$app
         package[c]=$package
         [ $API -le 30 ] && dir_app[c]=/data/app/$app-*/base.apk
         [ $API -ge 30 ] && dir_app[c]=/data/app/*/$package-*/base.apk
-        $use_aapt && { app=$(aapt d badging ${dir_app[c]} | grep 'application-label:'); app=${app#*:}; }
+        $use_aapt && {
+          app=$(aapt d badging ${dir_app[c]} | grep 'application-label:')
+          app=${app#*:}
+        }
         app1[c]=$(echo "$app" | tr ' ' '_' | tr -d "'")
-        echo "app${c}^=${app1[c]}^=${dir_app[c]}^=${package[c]}^=" >> $LISTFILE
-        c=$((c+1))
+        echo "app${c}^=${app1[c]}^=${dir_app[c]}^=${package[c]}^=" >>$LISTFILE
+        c=$((c + 1))
       fi
     done
     app2=($(echo "${app1[@]}" | sed "s/.*'//g"))
@@ -141,7 +156,10 @@ list_installed_apps() {
 
 # List systemized apps
 list_systemized_apps() {
-  systemized_apps=(); rev_dir=(); rev_label=(); rev_app=()
+  systemized_apps=()
+  rev_dir=()
+  rev_label=()
+  rev_app=()
   [ "$tmpmodpath" ] && MODDIRS="$MODDIR $path" || MODDIRS="$MODDIR"
   systemized_apps=($(find $MODDIRS -name "*.apk" -type f))
   cc=1
@@ -151,8 +169,12 @@ list_systemized_apps() {
     rev_label=${i%/*}
     rev_label[cc]=${rev_label##*/}
     rev_app[cc]=${rev_label[cc]}
-    $use_aapt && { rev_app=$(aapt d badging $i | grep 'application-label:'); rev_app=${rev_app#*:}; rev_app[cc]=$(echo $rev_app | tr ' ' '_' | tr -d "'"); }
-    cc=$((cc+1))
+    $use_aapt && {
+      rev_app=$(aapt d badging $i | grep 'application-label:')
+      rev_app=${rev_app#*:}
+      rev_app[cc]=$(echo $rev_app | tr ' ' '_' | tr -d "'")
+    }
+    cc=$((cc + 1))
   done
 }
 
@@ -173,7 +195,8 @@ systemize() {
     if [ "$PKG" ]; then
       name=$PKG
     else
-      name=${apkdir%/*}; name=${name##*/}
+      name=${apkdir%/*}
+      name=${name##*/}
       name=$(echo $name | tr -d ' ' | tr -d "'" | tr -d '*' | tr -d '-')
       $use_aapt && {
         name=$(aapt d badging $apkdir | head -n1 | awk '{print $2}')
@@ -184,12 +207,12 @@ systemize() {
   chk_apk_size $apkdir
   echo " Transfering ${apk}(${name}) to '$1'..."
   if [ -d $SYSTEM/app/${name} ] || [ -d $SYSTEM/priv-app/${name} ] || [ -d $MODDIR$SYSTEM2/app/${name} ] || [ -d $MODDIR$SYSTEM2/priv-app/${name} ]; then
-	$UNMOUNTIMG && {
-	  unmount_magisk_img
-	  IMG=$ORIGIMG
-	  MOUNTPATH=$ORIGMOUNTPATH
-	  MODDIR=$ORIGMODDIR
-	}
+    $UNMOUNTIMG && {
+      unmount_magisk_img
+      IMG=$ORIGIMG
+      MOUNTPATH=$ORIGMOUNTPATH
+      MODDIR=$ORIGMODDIR
+    }
     abort " App exists!"
   else
     mkdir -p ${MODDIR}${1}/${name}
@@ -203,11 +226,12 @@ systemize() {
       echo " Granting Permissions"
       mkdir -p $MODDIR$SYSTEM2/etc/permissions 2>/dev/null
       pp=0
-      app_perm=(); perm=()
+      app_perm=()
+      perm=()
       for i in $(aapt d permissions $apkdir | grep -v 'package:' | awk '{print $2}'); do
         _perm=$(echo ${i#*=} | tr -d "'")
         perm[pp]=$_perm
-        pp=$((pp+1))
+        pp=$((pp + 1))
       done
       app_perm=($(echo "${perm[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
       echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
@@ -215,21 +239,21 @@ systemize() {
 	Generated by $MODTITLE by $AUTHOR
 -->
 <permissions>
-    <privapp-permissions package=\"${name}\">" >> $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
+    <privapp-permissions package=\"${name}\">" >>$MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
       for i in ${app_perm[@]}; do
-        echo "        <permission name=\"$i\"/>" >> $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
+        echo "        <permission name=\"$i\"/>" >>$MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
       done
       echo "    </privapp-permissions>
-</permissions>" >> $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
+</permissions>" >>$MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
       chmod 644 $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${name}.xml
     }
     echo " ${name} - ${W}Done${N}"
-	$UNMOUNTIMG && {
-	  unmount_magisk_img
-	  IMG=$ORIGIMG
-	  MOUNTPATH=$ORIGMOUNTPATH
-	  MODDIR=$ORIGMODDIR
-	}
+    $UNMOUNTIMG && {
+      unmount_magisk_img
+      IMG=$ORIGIMG
+      MOUNTPATH=$ORIGMOUNTPATH
+      MODDIR=$ORIGMODDIR
+    }
   fi
 }
 
@@ -265,7 +289,8 @@ enter_apk_dir() {
         elif [ "$loc" == 2 ]; then
           systemize /system/priv-app
         elif [ "$loc" == 0 ]; then
-          echo " $name canceled"; exit
+          echo " $name canceled"
+          exit
         else
           abort "Invalid!"
         fi
@@ -305,7 +330,8 @@ enter_apk_name() {
     elif [ "$loc" == 2 ]; then
       installdir="priv-app"
     elif [ "$loc" == 0 ]; then
-      echo " $apklabel canceled"; exit
+      echo " $apklabel canceled"
+      exit
     else
       abort "Invalid!"
     fi
@@ -354,10 +380,10 @@ chk_apk_size() {
   apk_sizeM="$(du -m $dir_app | awk '{print $1}')"
   [ -d ${dir_app%/*}/lib ] && {
     lib_sizeM="$(du -ms ${dir_app%/*}/lib | awk '{print $1}')"
-    apk_sizeM="$((apk_sizeM+lib_sizeM))"
+    apk_sizeM="$((apk_sizeM + lib_sizeM))"
   }
   UNMOUNTIMG=false
-  if [ "$apk_sizeM" -gt "$((free_space-10))" ] && [ "$MOUNTPATH" == "/sbin/.magisk/img" ]; then
+  if [ "$apk_sizeM" -gt "$((free_space - 10))" ] && [ "$MOUNTPATH" == "/sbin/.magisk/img" ]; then
     echo " Checking App size - ${W}${apk_sizeM}M${N}"
     echo "- Insufficient $MOUNTPATH space!"
     echo "- APK size: ${apk_sizeM}M | $MOUNTPATH Free: ${free_space}M"
@@ -383,11 +409,11 @@ menu_list_systemized_apps() {
   title_div "Installed Apps"
   echo "$div"
   echo ""
-  for i in $(seq 0 $((${#app[@]}-1))); do
-    echo " $((i+1)) - ${W}${app[i]}${N}" | tr '_' ' '
+  for i in $(seq 0 $((${#app[@]} - 1))); do
+    echo " $((i + 1)) - ${W}${app[i]}${N}" | tr '_' ' '
   done
   echo ""
-  echo " ${Bl}To systemize multiple apps, enter multiple number. Example:${N} \"1 $(echo ${#app[$((${#app[@]}/3))]}) $(echo ${#app[$((${#app[@]}/2))]})\""
+  echo " ${Bl}To systemize multiple apps, enter multiple number. Example:${N} \"1 $(echo ${#app[$((${#app[@]} / 3))]}) $(echo ${#app[$((${#app[@]} / 2))]})\""
   echo " x - ${Bl}Back to Menu${N}"
   echo " r - ${Bl}Refresh list${N}"
   echo " 0 - ${Bl}Exit${N}"
@@ -396,13 +422,13 @@ menu_list_systemized_apps() {
   [ "$installed" == "x" ] && menu
   [ "$installed" == "r" ] && RESCAN=true && menu_list_systemized_apps
   for i in $installed; do
-    if [ "$i" -gt ${#app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ] ; then
+    if [ "$i" -gt ${#app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ]; then
       abort "Invalid!"
     elif [ "$i" == 0 ]; then
       exit
     else
       echo "$div"
-      i=$((i-1))
+      i=$((i - 1))
       echo "Systemizing ${W}${app[i]}${N}" | tr '_' ' '
       get_cfg ${app[i]}
       echo -n " Checking APK directory"
@@ -410,7 +436,9 @@ menu_list_systemized_apps() {
         echo " - ${W}OK${N}"
         apkdir=$DIR_APP
         apk=${apkdir##*/}
-        name=${apkdir%/*}; name=${name##*/}; name=$(echo $name | tr -d ' ' | tr -d "'" | tr -d '*' | tr -d '-')
+        name=${apkdir%/*}
+        name=${name##*/}
+        name=$(echo $name | tr -d ' ' | tr -d "'" | tr -d '*' | tr -d '-')
         echo " Checking package name - ${W}$PKG${N}"
         if [ $privapp == 1 ] && [ $sysapp == 1 ]; then
           echo " Where to install?"
@@ -421,7 +449,8 @@ menu_list_systemized_apps() {
           elif [ "$loc" == 2 ]; then
             systemize /system/priv-app
           elif [ "$loc" == 0 ]; then
-            echo " ${app[i]} canceled"; true
+            echo " ${app[i]} canceled"
+            true
           else
             abort "Invalid!"
           fi
@@ -450,18 +479,18 @@ revert_apps() {
   title_div "Revert"
   echo "$div"
   echo ""
-  for i in $(seq 1 $((${#rev_app[@]}-1))); do
+  for i in $(seq 1 $((${#rev_app[@]} - 1))); do
     echo " $i - ${W}${rev_app[i]}${N}" | tr '_' ' '
   done
   echo ""
-  echo " ${Bl}To systemize multiple apps, enter multiple number. Example:${N} \"1 ${#rev_app[$((${#rev_app[@]}/3))]} ${#rev_app[$((${#rev_app[@]}/2))]}\""
+  echo " ${Bl}To revert multiple apps, enter multiple number. Example:${N} \"1 ${#rev_app[$((${#rev_app[@]} / 3))]} ${#rev_app[$((${#rev_app[@]} / 2))]}\""
   echo " x - ${Bl}Back to Menu${N}"
   echo " 0 -  Exit"
   echo -n "[CHOICE]: "
   read revert
   [ "$revert" == "x" ] && menu
   for i in $revert; do
-    if [ "$i" -gt ${#rev_app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ] ; then
+    if [ "$i" -gt ${#rev_app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ]; then
       abort "Invalid!"
     elif [ "$i" == 0 ]; then
       exit
@@ -475,6 +504,37 @@ revert_apps() {
   echo -n "Return to menu? < y | n >: "
   read mchoice
   [ "$mchoice" == "y" ] && menu || exit
+}
+
+revert_app() {
+  list_systemized_apps 2>>$LOG
+  clear
+  echo "$div"
+  title_div "Revert"
+  echo "$div"
+  echo ""
+
+  if [ "$1" ]; then
+    pkg="$1"
+  else
+    abort " Please enter a package name"
+  fi
+
+  app_dirs=($(find $MODDIRS -name $pkg -type d))
+
+  if [ ${#app_dirs[@]} -eq 0 ]; then
+    abort " App not found!!"
+  fi
+
+  for app_dir in $app_dirs; do
+    echo "Reverting ${app_dir}..." | tr '_' ' '
+    rm -rf ${app_dir}
+  done
+
+  rm -rf $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${pkg}.xml >>$LOG 2>&1
+
+  echo "Reboot to apply changes"
+  exit
 }
 
 set_selinux() {
@@ -502,23 +562,26 @@ set_selinux() {
   echo -n "[CHOICE]: "
   read sechoice
   case "$sechoice" in
-    x|X) menu;;
-    c|C) if $faster_flag; then
-        echo "Using '-f' (faster) option, changes will not be applied!"
-		exit
-      elif $se_set; then
-        set_file_prop selinux false $MODDIR/module.prop
-        echo "Set to false"
-        echo "Exiting script to apply changes"
-        exit
-      else
-        set_file_prop selinux true $MODDIR/module.prop
-        echo "Set to true"
-        echo "Exiting script to apply changes"
-        exit
-      fi;;
-    0) exit;;
-    *) echo "Invalid!"; exit;;
+  x | X) menu ;;
+  c | C) if $faster_flag; then
+    echo "Using '-f' (faster) option, changes will not be applied!"
+    exit
+  elif $se_set; then
+    set_file_prop selinux false $MODDIR/module.prop
+    echo "Set to false"
+    echo "Exiting script to apply changes"
+    exit
+  else
+    set_file_prop selinux true $MODDIR/module.prop
+    echo "Set to true"
+    echo "Exiting script to apply changes"
+    exit
+  fi ;;
+  0) exit ;;
+  *)
+    echo "Invalid!"
+    exit
+    ;;
   esac
 }
 
@@ -544,50 +607,79 @@ menu() {
   echo -n "[CHOICE]: "
   read choice
   case "$choice" in
-    1) menu_list_systemized_apps;;
-    2) enter_apk_name; exit $?;;
-    3) enter_apk_dir; exit $?;;
-    4) revert_apps; exit $?;;
+  1) menu_list_systemized_apps ;;
+  2)
+    enter_apk_name
+    exit $?
+    ;;
+  3)
+    enter_apk_dir
+    exit $?
+    ;;
+  4)
+    revert_apps
+    exit $?
+    ;;
 
-    d|D) am start https://paypal.me/veez21 >>$LOG 2>&1;;
-    logs) upload_logs;;
-    s|S) set_selinux;;
-    0) exit;;
-    *) echo "Invalid!"; exit 1;;
+  d | D) am start https://paypal.me/veez21 >>$LOG 2>&1 ;;
+  logs) upload_logs ;;
+  s | S) set_selinux ;;
+  0) exit ;;
+  *)
+    echo "Invalid!"
+    exit 1
+    ;;
   esac
 }
 
 case "$1" in
-  -a) shift
-    for i in "$@"; do
-          [ $API -lt 30 ] && app_path="/data/app/${i}-*/base.apk"
-          [ $API -ge 30 ] && app_path="/data/app/*/${i}-*/base.apk"
-	  [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$app_path" || systemize /system/app "$app_path" "$i"
-	  echo "$div"
-	done
-	exit;;
-  -p) shift
-    for i in "$@"; do
-          [ $API -lt 30 ] && app_path="/data/app/${i}-*/base.apk"
-          [ $API -ge 30 ] && app_path="/data/app/*/${i}-*/base.apk"
-	  [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$app_path"
-	  echo "$div"
-	done
-	exit;;
-  -d) shift
-    for i in "$@"; do
-	  [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$i" || systemize /system/app "$i"
-	  echo "$div"
-	done
-	exit;;
-  -l) list_systemized_apps 2>>$LOG
-    echo
-    for i in ${!rev_dir[@]}; do
-      title_div "App $i"
-      echo "Name\t: $(echo ${rev_app[i]}| tr '_' ' ')\nLabel\t: ${rev_label[i]}\nDirectory\t: $(echo ${rev_dir[i]} | sed 's/.*\/system\///g')" | expand -t 10
-    done
-    exit;;
-  -h|--help) help_me;;
+-a)
+  shift
+  for i in "$@"; do
+    [ $API -lt 30 ] && app_path="/data/app/${i}-*/base.apk"
+    [ $API -ge 30 ] && app_path="/data/app/*/${i}-*/base.apk"
+    [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$app_path" || systemize /system/app "$app_path" "$i"
+    echo "$div"
+  done
+  exit
+  ;;
+-p)
+  shift
+  for i in "$@"; do
+    [ $API -lt 30 ] && app_path="/data/app/${i}-*/base.apk"
+    [ $API -ge 30 ] && app_path="/data/app/*/${i}-*/base.apk"
+    [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$app_path"
+    echo "$div"
+  done
+  exit
+  ;;
+-r)
+  shift
+  for i in "$@"; do
+    app_path="$i"
+    revert_app "$app_path"
+    echo "$div"
+  done
+  exit
+  ;;
+-d)
+  shift
+  for i in "$@"; do
+    [ -d $SYSTEM/priv-app ] && systemize /system/priv-app "$i" || systemize /system/app "$i"
+    echo "$div"
+  done
+  exit
+  ;;
+-l)
+  list_systemized_apps 2>>$LOG
+  echo
+  for i in ${!rev_dir[@]}; do
+    title_div "App $i"
+    echo "Name\t: $(echo ${rev_app[i]} | tr '_' ' ')\nLabel\t: ${rev_label[i]}\nDirectory\t: $(echo ${rev_dir[i]} | sed 's/.*\/system\///g')" | expand -t 10
+  done
+  exit
+  ;;
+-h | --help) help_me ;;
 esac
 
 menu
